# Generated by Django 5.0.4 on 2024-05-02 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_downloadedsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('tipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id_user_playlist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(max_length=500)),
                ('jumlah_lagu', models.IntegerField()),
                ('tanggal_dibuat', models.DateField()),
                ('total_durasi', models.IntegerField(default=0)),
                ('email_pembuat', models.ForeignKey(db_column='email_pembuat', on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
            options={
                'unique_together': {('email_pembuat', 'id_user_playlist')},
            },
        ),
        migrations.CreateModel(
            name='AkunPlaySong',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(db_column='email_pemain', on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('email_pemain', 'id_song', 'waktu')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('id_playlist', 'id_song')},
            },
        ),
        migrations.CreateModel(
            name='Royalti',
            fields=[
                ('id_pemilik_hak_cipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.pemilikhakcipta')),
                ('jumlah', models.IntegerField()),
                ('id_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.song')),
            ],
            options={
                'unique_together': {('id_pemilik_hak_cipta', 'id_song')},
            },
        ),
        migrations.CreateModel(
            name='AkunPlayUserPlaylist',
            fields=[
                ('waktu', models.DateTimeField(primary_key=True, serialize=False)),
                ('email_pemain', models.ForeignKey(db_column='email_pemain', on_delete=django.db.models.deletion.CASCADE, to='main.akun')),
                ('email_pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_creator', to='main.akun')),
                ('id_user_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userplaylist')),
            ],
            options={
                'unique_together': {('email_pemain', 'id_user_playlist', 'waktu')},
            },
        ),
    ]
