# Generated by Django 5.0.4 on 2024-05-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_playlist_chart_userplaylist_akunplaysong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedsong',
            name='id_song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.song'),
        ),
        migrations.AlterField(
            model_name='royalti',
            name='id_pemilik_hak_cipta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.pemilikhakcipta'),
        ),
    ]
