# Generated by Django 5.0.4 on 2024-05-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_downloadedsong_id_song_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadedsong',
            options={'managed': False},
        ),
    ]
