# Generated by Django 5.0.4 on 2024-05-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_downloadedsong_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadedsong',
            options={},
        ),
    ]
