# Generated by Django 4.2.4 on 2024-05-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=10)),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('home_city', models.CharField(max_length=100)),
                ('is_podcaster', models.BooleanField(default=False)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_songwriter', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
